### ISSUE TITLE
dict as data in db

### ISSUE THREAD

**Issue by zv09** [pysonDB/pysonDB-v2#11]
is any plan in code to manage db fields as dicts, like

{
    "version": 2,
    "keys": [
        "age",
        "knows_python",
        "name",
        "codes[{}]"
    ],
    "data": {
        "231541323453553701": {
            "name": "adwaith",
            "age": 4,
            "knows_python": true
            _**"codes" : {'sape': 4139, 'guido': 4127, 'jack': 4098}**_
        }
    }
}

**Comment by builder555** [comment]
@zv09 what would be the advantage of using pysondb if the data is to be managed as a regular dictionary without using class interfaces?

**Comment by zv09** [comment]
ok, how to store wrapped data ? 
like "codes" : {'sape': 4139, 'guido': 4127, 'jack': 4098}

**Comment by builder555** [comment]
```
>>> from pysondb import PysonDB
>>> db = PysonDB('test.json')
>>> db.add({"codes" : {'sape': 4139, 'guido': 4127, 'jack': 4098}})
'281990590628898407'
>>> db.get_all()
{'281990590628898407': {'codes': {'sape': 4139, 'guido': 4127, 'jack': 4098}}}
```

**Comment by zv09** [comment]
well, it's simple.. thx u v m
